config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks
  end
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :name, presence: true

  def percent_complete
    return 0 if tasks_count.zero?

    (100 * completed_items.to_f / tasks_count).round(1)
  end

  def completed_items
    @completed_items ||= tasks.completed.count
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project, counter_cache: true

  validates :description, presence: true

  scope :completed, -> { where(completed: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @task = Task.new
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            @project,
            partial: "projects/form",
            locals: { project: @project }
          )
        end
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_path(@task.project), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoRealtime</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
          <div class="card mt-5 p-5">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/projects/_edit_form.html.erb
<%= form_with(model: project, class: "row g-2") do |form| %>
  <% if project.errors.any? %>
    <div class="alert alert-danger">
      <ul class="m-0">
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-auto">
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="col-auto">
    <%= form.submit "Update", class: "btn btn-success" %>
  </div>

  <%= link_to "Cancel", project_path(project) %>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div class="alert alert-danger">
      <ul class="m-0">
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="d-flex align-items-center justify-content-between mb-3">
    <%= form.submit class: "btn btn-success" %>
    <%= link_to "Cancel", projects_path %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <%= link_to project do %>
    <h4><%= project.name %> (<%= project.tasks_count %>)</h4>
  <% end %>
</div>

app/views/projects/_project_counts.html.erb
<div id="project-<%= project.id %>-counts" class="mb-3">
  <p class="text-muted m-0">
    <%= project.percent_complete %>% complete (<%= project.completed_items %>/<%= project.tasks_count %>)
  </p>
  <div class="progress">
    <div class="progress-bar bg-success" role="progressbar" style="width: <%= project.percent_complete %>%" aria-valuenow="<%= project.percent_complete %>" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
</div>

app/views/projects/create.turbo_stream.erb
<%= turbo_stream.append "projects", @project %>
<%= turbo_stream.update Project.new, "" %>

app/views/projects/edit.html.erb
<%= turbo_frame_tag :project_name do %>
  <%= render "edit_form", project: @project %>
<% end %>

app/views/projects/index.html.erb
<div>
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h1>Projects</h1>
    <%= link_to "New project", new_project_path,
                               class: "btn btn-secondary",
                               data: { turbo_frame: dom_id(Project.new) } %>
  </div>

  <%= turbo_frame_tag Project.new %>

  <div id="projects">
    <%= render @projects %>
  </div>
</div>

app/views/projects/new.html.erb
<%= turbo_frame_tag @project do %>
  <%= render "form", project: @project %>
<% end %>

app/views/projects/show.html.erb
<div>
  <div class="d-flex align-items-center justify-content-between mb-3">
    <%= turbo_frame_tag :project_name do %>
      <%= link_to edit_project_path(@project) do %>
        <h1><%= @project.name %></h1>
      <% end %>
    <% end %>
    <%= link_to "New task", new_project_task_path(@project),
                            class: "btn btn-secondary",
                            data: { turbo_frame: "new_task_form" } %>
  </div>

  <%= render "projects/project_counts", project: @project %>

  <%= turbo_frame_tag "new_task_form" %>

  <% if @project.tasks.any? %>
    <ul id="project-<%= @project.id %>-tasks" class="list-group">
      <% @project.tasks.each do |task| %>
        <%= render partial: 'tasks/task', locals: { project: @project, task: task } %>
      <% end %>
    </div>
  <% else %>
    <div class="alert alert-dark">
      <h3>No Tasks</h3>
    </div>
  <% end %>

  <div class="d-flex align-items-center justify-content-between mt-5">
    <%= link_to "Back to projects", projects_path %>

    <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-danger", data: { turbo_confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [project, task],
              html: { data: { controller: 'tasks' }},
              local: false) do |form| %>
  <% if task.errors.any? %>
    <div class="alert alert-danger">
      <ul class="m-0">
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_area :description, class: "form-control", rows: 3, placeholder: "What do you want to do..." %>
  </div>

  <div class="d-flex align-items-center justify-content-between mb-3">
    <%= form.submit "Create", id: "submit-tasks", class: "btn btn-success", data: { reflex: 'click->Tasks#create' } %>
    <%= link_to "Cancel", project_path(project) %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag task do %>
  <li class="list-group-item">
    <div class="d-flex alig-items-center justify-content-between">
      <div class="d-flex align-items-center">
        <%= check_box_tag "task-#{task.id}-checkbox",
                          task.completed,
                          task.completed,
                          { data: { reflex: 'change->Tasks#toggle', task_id: task.id }, class: "form-check-input" } %>
        <p class="m-0 ms-2 <%= task.completed ? "text-decoration-line-through" : "" %>">
          <%= task.description %>
        </p>
      </div>
      <div>
        <%= button_to "Destroy", project_task_path(project, task), method: :delete, class: "btn btn-danger btn-sm" %>
      </div>
    </div>
  </li>
<% end %>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.append "project-#{@project.id}-tasks" do %>
  <%= render partial: 'tasks/task', locals: { project: @project, task: @task } %>
<% end %>
<%= turbo_stream.update "new_task_form", "" %>
<%= turbo_stream.replace "project-#{@project.id}-counts" do %>
  <%= render "projects/project_counts", project: @project %>
<% end %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove(@task) %>
<%= turbo_stream.replace "project-#{@task.project.id}-counts" do %>
  <%= render "projects/project_counts", project: @task.project %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<%= turbo_frame_tag "new_task_form" do %>
  <%= render "form", project: @project, task: @task %>
<% end %>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace @task do %>
  <%= render partial: 'tasks/task', locals: { project: @task.project, task: @task } %>
<% end %>